// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --prefix-filecheck-ir-name TMP_ --version 6

// RUN: %clang_cc1 -triple arm64e -fbounds-safety -fptrauth-intrinsics -emit-llvm %s -o - | FileCheck --check-prefix=C %s
// RUN: %clang_cc1 -triple arm64e -fbounds-safety -fptrauth-intrinsics -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefix=OBJC %s

// rdar://182733053
//
// A ptrauth builtin operand may be a wide pointer (__indexable /
// __bidi_indexable) under -fbounds-safety. Wide pointers are aggregates, so
// EmitScalarExpr() asserted on them:
//
//   Assertion failed: (E && hasScalarEvaluationKind(E->getType()) &&
//                      "Invalid scalar expression to emit"),
//   function EmitScalarExpr, file CGExprScalar.cpp
//
// This broke the liblibc arm64e build, whose sign_destructors() passes
// `&entries[i]` -- a __bidi_indexable derived from a __sized_by parameter -- as
// the discriminator of ptrauth_blend_discriminator().
//
// Root cause: unlike every other callee taking a raw pointer, these builtins
// got no implicit CK_BoundsSafetyPointerCast, because checkPointerAuthValue()
// discarded the builtin's declared `void *` parameter and substituted the
// argument's own type, leaving convertArgumentToType() with nothing to do.
//
// A ptrauth operation acts on the raw address, so the operand is now converted
// to a raw-layout pointer and the bounds are dropped. That is exactly what the
// assertions-disabled compiler already emitted for this shape, so the generated
// code is unchanged for code that builds today. In particular no bounds check is
// introduced: the checks below are exhaustive per function, so an added
// llvm.ubsantrap would show up as a mismatch. The only traps present are
// sign_destructors()'s own `entries[i]` subscript checks, which are unrelated to
// the discriminator operand.
//
// Without the fix every function here crashes the compiler, and the global at
// the top fails in the constant-emission path instead.

#include <ptrcheck.h>

unsigned long a[10];

// The constant-emission path. Before the fix a wide-pointer operand here failed
// with "Invalid constantexpr bitcast!" in ConstantEmitter::tryEmitPrivate --
// a different symptom of the same missing cast, now emitted as a signed
// constant. Placed before the function checks because globals appear at the top
// of the module and FileCheck only scans forward.
// C: @sign_const = constant ptr @a.ptrauth
// OBJC: @sign_const = constant ptr @a.ptrauth
void *__unsafe_indexable const sign_const =
    __builtin_ptrauth_sign_constant(&a[0], 2, 0);

//===----------------------------------------------------------------------===//
// Discriminator slots: the result is an integer, so only the address is used.
//===----------------------------------------------------------------------===//

// The reduced form of the liblibc failure.
// C-LABEL: define dso_local i64 @blend_addrof(
// C-SAME: ) #[[ATTR0:[0-9]+]] {
// C-NEXT:  [[ENTRY:.*:]]
// C-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// C-NEXT:    store ptr @a, ptr [[TMP0]], align 8
// C-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// C-NEXT:    store ptr getelementptr inbounds nuw (i8, ptr @a, i64 80), ptr [[TMP1]], align 8
// C-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// C-NEXT:    store ptr @a, ptr [[TMP2]], align 8
// C-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// C-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP3]], align 8
// C-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i64, ptr [[TMP4]], i64 0
// C-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// C-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP5]], align 8
// C-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// C-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
// C-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// C-NEXT:    store ptr [[TMP7]], ptr [[TMP8]], align 8
// C-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// C-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[TMP9]], align 8
// C-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// C-NEXT:    store ptr [[TMP10]], ptr [[TMP11]], align 8
// C-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// C-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// C-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// C-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// C-NEXT:    [[TMP12:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// C-NEXT:    [[TMP13:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[TMP12]], i64 42)
// C-NEXT:    ret i64 [[TMP13]]
//
// OBJC-LABEL: define dso_local i64 @blend_addrof(
// OBJC-SAME: ) #[[ATTR0:[0-9]+]] {
// OBJC-NEXT:  [[ENTRY:.*:]]
// OBJC-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// OBJC-NEXT:    store ptr @a, ptr [[TMP0]], align 8
// OBJC-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// OBJC-NEXT:    store ptr getelementptr inbounds nuw (i8, ptr @a, i64 80), ptr [[TMP1]], align 8
// OBJC-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// OBJC-NEXT:    store ptr @a, ptr [[TMP2]], align 8
// OBJC-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// OBJC-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP3]], align 8
// OBJC-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i64, ptr [[TMP4]], i64 0
// OBJC-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OBJC-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP5]], align 8
// OBJC-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// OBJC-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
// OBJC-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OBJC-NEXT:    store ptr [[TMP7]], ptr [[TMP8]], align 8
// OBJC-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// OBJC-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[TMP9]], align 8
// OBJC-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OBJC-NEXT:    store ptr [[TMP10]], ptr [[TMP11]], align 8
// OBJC-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OBJC-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OBJC-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OBJC-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// OBJC-NEXT:    [[TMP12:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// OBJC-NEXT:    [[TMP13:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[TMP12]], i64 42)
// OBJC-NEXT:    ret i64 [[TMP13]]
//
unsigned long blend_addrof(void) {
  return __builtin_ptrauth_blend_discriminator(&a[0], 42);
}

// The liblibc shape itself: __bidi_indexable derived from a __sized_by param.
// The subscript keeps its own bounds checks; only the discriminator drops them.
// C-LABEL: define dso_local void @sign_destructors(
// C-SAME: ptr noundef [[ENTRIES:%.*]], i64 noundef [[SZ:%.*]]) #[[ATTR0]] {
// C-NEXT:  [[ENTRY:.*:]]
// C-NEXT:    [[ENTRIES_ADDR:%.*]] = alloca ptr, align 8
// C-NEXT:    [[SZ_ADDR:%.*]] = alloca i64, align 8
// C-NEXT:    [[I:%.*]] = alloca i64, align 8
// C-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    [[AGG_TEMP2:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    store ptr [[ENTRIES]], ptr [[ENTRIES_ADDR]], align 8
// C-NEXT:    store i64 [[SZ]], ptr [[SZ_ADDR]], align 8
// C-NEXT:    store i64 0, ptr [[I]], align 8
// C-NEXT:    br label %[[FOR_COND:.*]]
// C:       [[FOR_COND]]:
// C-NEXT:    [[TMP0:%.*]] = load i64, ptr [[I]], align 8
// C-NEXT:    [[TMP1:%.*]] = load i64, ptr [[SZ_ADDR]], align 8
// C-NEXT:    [[DIV:%.*]] = udiv i64 [[TMP1]], 8
// C-NEXT:    [[CMP:%.*]] = icmp ult i64 [[TMP0]], [[DIV]]
// C-NEXT:    br i1 [[CMP]], label %[[FOR_BODY:.*]], label %[[FOR_END:.*]]
// C:       [[FOR_BODY]]:
// C-NEXT:    [[TMP2:%.*]] = load i64, ptr [[I]], align 8
// C-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[ENTRIES_ADDR]], align 8
// C-NEXT:    [[TMP4:%.*]] = load i64, ptr [[SZ_ADDR]], align 8
// C-NEXT:    [[CMP1:%.*]] = icmp sge i64 [[TMP4]], 0
// C-NEXT:    call void @llvm.assume(i1 [[CMP1]])
// C-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP3]], i64 [[TMP4]]
// C-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// C-NEXT:    store ptr [[TMP3]], ptr [[TMP5]], align 8
// C-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// C-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP6]], align 8
// C-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// C-NEXT:    store ptr [[TMP3]], ptr [[TMP7]], align 8
// C-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// C-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[TMP8]], align 8
// C-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i64, ptr [[TMP9]], i64 [[TMP2]]
// C-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// C-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP10]], align 8
// C-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// C-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[TMP11]], align 8
// C-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// C-NEXT:    store ptr [[TMP12]], ptr [[TMP13]], align 8
// C-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// C-NEXT:    [[TMP15:%.*]] = load ptr, ptr [[TMP14]], align 8
// C-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// C-NEXT:    store ptr [[TMP15]], ptr [[TMP16]], align 8
// C-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// C-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// C-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// C-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// C-NEXT:    [[TMP17:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// C-NEXT:    [[TMP18:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[TMP17]], i64 42)
// C-NEXT:    [[TMP19:%.*]] = load ptr, ptr [[ENTRIES_ADDR]], align 8
// C-NEXT:    [[TMP20:%.*]] = load i64, ptr [[SZ_ADDR]], align 8
// C-NEXT:    [[CMP3:%.*]] = icmp sge i64 [[TMP20]], 0
// C-NEXT:    call void @llvm.assume(i1 [[CMP3]])
// C-NEXT:    [[ADD_PTR4:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP19]], i64 [[TMP20]]
// C-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0
// C-NEXT:    store ptr [[TMP19]], ptr [[TMP21]], align 8
// C-NEXT:    [[TMP22:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1
// C-NEXT:    store ptr [[ADD_PTR4]], ptr [[TMP22]], align 8
// C-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 2
// C-NEXT:    store ptr [[TMP19]], ptr [[TMP23]], align 8
// C-NEXT:    [[WIDE_PTR_PTR_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0
// C-NEXT:    [[WIDE_PTR_PTR6:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR5]], align 8
// C-NEXT:    [[TMP24:%.*]] = load i64, ptr [[I]], align 8
// C-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i64, ptr [[WIDE_PTR_PTR6]], i64 [[TMP24]]
// C-NEXT:    [[WIDE_PTR_UB_ADDR7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1
// C-NEXT:    [[WIDE_PTR_UB8:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR7]], align 8
// C-NEXT:    [[WIDE_PTR_LB_ADDR9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 2
// C-NEXT:    [[WIDE_PTR_LB10:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR9]], align 8
// C-NEXT:    [[TMP25:%.*]] = getelementptr i64, ptr [[ARRAYIDX]], i64 1, !annotation [[META4:![0-9]+]]
// C-NEXT:    [[TMP26:%.*]] = icmp ule ptr [[TMP25]], [[WIDE_PTR_UB8]], !annotation [[META4]]
// C-NEXT:    br i1 [[TMP26]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF5:![0-9]+]], !annotation [[META4]]
// C:       [[TRAP]]:
// C-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR6:[0-9]+]], !annotation [[META4]]
// C-NEXT:    unreachable, !annotation [[META4]]
// C:       [[CONT]]:
// C-NEXT:    [[TMP27:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP25]], !annotation [[META4]]
// C-NEXT:    br i1 [[TMP27]], label %[[CONT12:.*]], label %[[TRAP11:.*]], !prof [[PROF5]], !annotation [[META4]]
// C:       [[TRAP11]]:
// C-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR6]], !annotation [[META4]]
// C-NEXT:    unreachable, !annotation [[META4]]
// C:       [[CONT12]]:
// C-NEXT:    [[TMP28:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB10]], !annotation [[META6:![0-9]+]]
// C-NEXT:    br i1 [[TMP28]], label %[[CONT14:.*]], label %[[TRAP13:.*]], !prof [[PROF5]], !annotation [[META6]]
// C:       [[TRAP13]]:
// C-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR6]], !annotation [[META6]]
// C-NEXT:    unreachable, !annotation [[META6]]
// C:       [[CONT14]]:
// C-NEXT:    store i64 [[TMP18]], ptr [[ARRAYIDX]], align 8
// C-NEXT:    br label %[[FOR_INC:.*]]
// C:       [[FOR_INC]]:
// C-NEXT:    [[TMP29:%.*]] = load i64, ptr [[I]], align 8
// C-NEXT:    [[INC:%.*]] = add i64 [[TMP29]], 1
// C-NEXT:    store i64 [[INC]], ptr [[I]], align 8
// C-NEXT:    br label %[[FOR_COND]], !llvm.loop [[LOOP7:![0-9]+]]
// C:       [[FOR_END]]:
// C-NEXT:    ret void
//
// OBJC-LABEL: define dso_local void @sign_destructors(
// OBJC-SAME: ptr noundef [[ENTRIES:%.*]], i64 noundef [[SZ:%.*]]) #[[ATTR0]] {
// OBJC-NEXT:  [[ENTRY:.*:]]
// OBJC-NEXT:    [[ENTRIES_ADDR:%.*]] = alloca ptr, align 8
// OBJC-NEXT:    [[SZ_ADDR:%.*]] = alloca i64, align 8
// OBJC-NEXT:    [[I:%.*]] = alloca i64, align 8
// OBJC-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    [[AGG_TEMP2:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    store ptr [[ENTRIES]], ptr [[ENTRIES_ADDR]], align 8
// OBJC-NEXT:    store i64 [[SZ]], ptr [[SZ_ADDR]], align 8
// OBJC-NEXT:    store i64 0, ptr [[I]], align 8
// OBJC-NEXT:    br label %[[FOR_COND:.*]]
// OBJC:       [[FOR_COND]]:
// OBJC-NEXT:    [[TMP0:%.*]] = load i64, ptr [[I]], align 8
// OBJC-NEXT:    [[TMP1:%.*]] = load i64, ptr [[SZ_ADDR]], align 8
// OBJC-NEXT:    [[DIV:%.*]] = udiv i64 [[TMP1]], 8
// OBJC-NEXT:    [[CMP:%.*]] = icmp ult i64 [[TMP0]], [[DIV]]
// OBJC-NEXT:    br i1 [[CMP]], label %[[FOR_BODY:.*]], label %[[FOR_END:.*]]
// OBJC:       [[FOR_BODY]]:
// OBJC-NEXT:    [[TMP2:%.*]] = load i64, ptr [[I]], align 8
// OBJC-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[ENTRIES_ADDR]], align 8
// OBJC-NEXT:    [[TMP4:%.*]] = load i64, ptr [[SZ_ADDR]], align 8
// OBJC-NEXT:    [[CMP1:%.*]] = icmp sge i64 [[TMP4]], 0
// OBJC-NEXT:    call void @llvm.assume(i1 [[CMP1]])
// OBJC-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP3]], i64 [[TMP4]]
// OBJC-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// OBJC-NEXT:    store ptr [[TMP3]], ptr [[TMP5]], align 8
// OBJC-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// OBJC-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP6]], align 8
// OBJC-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// OBJC-NEXT:    store ptr [[TMP3]], ptr [[TMP7]], align 8
// OBJC-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// OBJC-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[TMP8]], align 8
// OBJC-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i64, ptr [[TMP9]], i64 [[TMP2]]
// OBJC-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OBJC-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP10]], align 8
// OBJC-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// OBJC-NEXT:    [[TMP12:%.*]] = load ptr, ptr [[TMP11]], align 8
// OBJC-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OBJC-NEXT:    store ptr [[TMP12]], ptr [[TMP13]], align 8
// OBJC-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// OBJC-NEXT:    [[TMP15:%.*]] = load ptr, ptr [[TMP14]], align 8
// OBJC-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OBJC-NEXT:    store ptr [[TMP15]], ptr [[TMP16]], align 8
// OBJC-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OBJC-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OBJC-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OBJC-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// OBJC-NEXT:    [[TMP17:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// OBJC-NEXT:    [[TMP18:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[TMP17]], i64 42)
// OBJC-NEXT:    [[TMP19:%.*]] = load ptr, ptr [[ENTRIES_ADDR]], align 8
// OBJC-NEXT:    [[TMP20:%.*]] = load i64, ptr [[SZ_ADDR]], align 8
// OBJC-NEXT:    [[CMP3:%.*]] = icmp sge i64 [[TMP20]], 0
// OBJC-NEXT:    call void @llvm.assume(i1 [[CMP3]])
// OBJC-NEXT:    [[ADD_PTR4:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP19]], i64 [[TMP20]]
// OBJC-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0
// OBJC-NEXT:    store ptr [[TMP19]], ptr [[TMP21]], align 8
// OBJC-NEXT:    [[TMP22:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1
// OBJC-NEXT:    store ptr [[ADD_PTR4]], ptr [[TMP22]], align 8
// OBJC-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 2
// OBJC-NEXT:    store ptr [[TMP19]], ptr [[TMP23]], align 8
// OBJC-NEXT:    [[WIDE_PTR_PTR_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 0
// OBJC-NEXT:    [[WIDE_PTR_PTR6:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR5]], align 8
// OBJC-NEXT:    [[TMP24:%.*]] = load i64, ptr [[I]], align 8
// OBJC-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i64, ptr [[WIDE_PTR_PTR6]], i64 [[TMP24]]
// OBJC-NEXT:    [[WIDE_PTR_UB_ADDR7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 1
// OBJC-NEXT:    [[WIDE_PTR_UB8:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR7]], align 8
// OBJC-NEXT:    [[WIDE_PTR_LB_ADDR9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP2]], i32 0, i32 2
// OBJC-NEXT:    [[WIDE_PTR_LB10:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR9]], align 8
// OBJC-NEXT:    [[TMP25:%.*]] = getelementptr i64, ptr [[ARRAYIDX]], i64 1, !annotation [[META10:![0-9]+]]
// OBJC-NEXT:    [[TMP26:%.*]] = icmp ule ptr [[TMP25]], [[WIDE_PTR_UB8]], !annotation [[META10]]
// OBJC-NEXT:    br i1 [[TMP26]], label %[[CONT:.*]], label %[[TRAP:.*]], !prof [[PROF11:![0-9]+]], !annotation [[META10]]
// OBJC:       [[TRAP]]:
// OBJC-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR6:[0-9]+]], !annotation [[META10]]
// OBJC-NEXT:    unreachable, !annotation [[META10]]
// OBJC:       [[CONT]]:
// OBJC-NEXT:    [[TMP27:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP25]], !annotation [[META10]]
// OBJC-NEXT:    br i1 [[TMP27]], label %[[CONT12:.*]], label %[[TRAP11:.*]], !prof [[PROF11]], !annotation [[META10]]
// OBJC:       [[TRAP11]]:
// OBJC-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR6]], !annotation [[META10]]
// OBJC-NEXT:    unreachable, !annotation [[META10]]
// OBJC:       [[CONT12]]:
// OBJC-NEXT:    [[TMP28:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB10]], !annotation [[META12:![0-9]+]]
// OBJC-NEXT:    br i1 [[TMP28]], label %[[CONT14:.*]], label %[[TRAP13:.*]], !prof [[PROF11]], !annotation [[META12]]
// OBJC:       [[TRAP13]]:
// OBJC-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR6]], !annotation [[META12]]
// OBJC-NEXT:    unreachable, !annotation [[META12]]
// OBJC:       [[CONT14]]:
// OBJC-NEXT:    store i64 [[TMP18]], ptr [[ARRAYIDX]], align 8
// OBJC-NEXT:    br label %[[FOR_INC:.*]]
// OBJC:       [[FOR_INC]]:
// OBJC-NEXT:    [[TMP29:%.*]] = load i64, ptr [[I]], align 8
// OBJC-NEXT:    [[INC:%.*]] = add i64 [[TMP29]], 1
// OBJC-NEXT:    store i64 [[INC]], ptr [[I]], align 8
// OBJC-NEXT:    br label %[[FOR_COND]], !llvm.loop [[LOOP13:![0-9]+]]
// OBJC:       [[FOR_END]]:
// OBJC-NEXT:    ret void
//
void sign_destructors(unsigned long *__sized_by(sz) entries, unsigned long sz) {
  for (unsigned long i = 0; i < sz / sizeof(*entries); ++i)
    entries[i] = __builtin_ptrauth_blend_discriminator(&entries[i], 42);
}

// C-LABEL: define dso_local i64 @blend_bidi(
// C-SAME: ptr nofreeobj noundef align 8 dead_on_return dereferenceable(24) [[P:%.*]]) #[[ATTR0]] {
// C-NEXT:  [[ENTRY:.*:]]
// C-NEXT:    [[P_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// C-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    store ptr [[P]], ptr [[P_INDIRECT_ADDR]], align 8
// C-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[P]], i64 24, i1 false)
// C-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// C-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// C-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// C-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// C-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// C-NEXT:    [[TMP1:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[TMP0]], i64 42)
// C-NEXT:    ret i64 [[TMP1]]
//
// OBJC-LABEL: define dso_local i64 @blend_bidi(
// OBJC-SAME: ptr nofreeobj noundef align 8 dead_on_return dereferenceable(24) [[P:%.*]]) #[[ATTR0]] {
// OBJC-NEXT:  [[ENTRY:.*:]]
// OBJC-NEXT:    [[P_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// OBJC-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    store ptr [[P]], ptr [[P_INDIRECT_ADDR]], align 8
// OBJC-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[P]], i64 24, i1 false)
// OBJC-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OBJC-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OBJC-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OBJC-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// OBJC-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// OBJC-NEXT:    [[TMP1:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[TMP0]], i64 42)
// OBJC-NEXT:    ret i64 [[TMP1]]
//
unsigned long blend_bidi(unsigned long *__bidi_indexable p) {
  return __builtin_ptrauth_blend_discriminator(p, 42);
}

// __indexable has an upper bound but no lower bound.
// C-LABEL: define dso_local i64 @blend_indexable(
// C-SAME: [2 x i64] noundef [[P_COERCE:%.*]]) #[[ATTR0]] {
// C-NEXT:  [[ENTRY:.*:]]
// C-NEXT:    [[P:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// C-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// C-NEXT:    store [2 x i64] [[P_COERCE]], ptr [[P]], align 8
// C-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[P]], i64 16, i1 false)
// C-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// C-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// C-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// C-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// C-NEXT:    [[TMP1:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[TMP0]], i64 42)
// C-NEXT:    ret i64 [[TMP1]]
//
// OBJC-LABEL: define dso_local i64 @blend_indexable(
// OBJC-SAME: [2 x i64] noundef [[P_COERCE:%.*]]) #[[ATTR0]] {
// OBJC-NEXT:  [[ENTRY:.*:]]
// OBJC-NEXT:    [[P:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// OBJC-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// OBJC-NEXT:    store [2 x i64] [[P_COERCE]], ptr [[P]], align 8
// OBJC-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[P]], i64 16, i1 false)
// OBJC-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OBJC-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OBJC-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// OBJC-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// OBJC-NEXT:    [[TMP1:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[TMP0]], i64 42)
// OBJC-NEXT:    ret i64 [[TMP1]]
//
unsigned long blend_indexable(unsigned long *__indexable p) {
  return __builtin_ptrauth_blend_discriminator(p, 42);
}

// Both operands of sign_generic_data accept a pointer.
// C-LABEL: define dso_local i64 @sign_generic_wide(
// C-SAME: ptr nofreeobj noundef align 8 dead_on_return dereferenceable(24) [[P:%.*]]) #[[ATTR0]] {
// C-NEXT:  [[ENTRY:.*:]]
// C-NEXT:    [[P_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// C-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    store ptr [[P]], ptr [[P_INDIRECT_ADDR]], align 8
// C-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[P]], i64 24, i1 false)
// C-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// C-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// C-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// C-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// C-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// C-NEXT:    store ptr @a, ptr [[TMP0]], align 8
// C-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// C-NEXT:    store ptr getelementptr inbounds nuw (i8, ptr @a, i64 80), ptr [[TMP1]], align 8
// C-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// C-NEXT:    store ptr @a, ptr [[TMP2]], align 8
// C-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// C-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP3]], align 8
// C-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i64, ptr [[TMP4]], i64 1
// C-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// C-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP5]], align 8
// C-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// C-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
// C-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// C-NEXT:    store ptr [[TMP7]], ptr [[TMP8]], align 8
// C-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// C-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[TMP9]], align 8
// C-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2
// C-NEXT:    store ptr [[TMP10]], ptr [[TMP11]], align 8
// C-NEXT:    [[WIDE_PTR_PTR_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// C-NEXT:    [[WIDE_PTR_PTR3:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR2]], align 8
// C-NEXT:    [[WIDE_PTR_UB_ADDR4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// C-NEXT:    [[WIDE_PTR_UB5:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR4]], align 8
// C-NEXT:    [[WIDE_PTR_LB_ADDR6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2
// C-NEXT:    [[WIDE_PTR_LB7:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR6]], align 8
// C-NEXT:    [[TMP12:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// C-NEXT:    [[TMP13:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR3]] to i64
// C-NEXT:    [[TMP14:%.*]] = call i64 @llvm.ptrauth.sign.generic(i64 [[TMP12]], i64 [[TMP13]])
// C-NEXT:    ret i64 [[TMP14]]
//
// OBJC-LABEL: define dso_local i64 @sign_generic_wide(
// OBJC-SAME: ptr nofreeobj noundef align 8 dead_on_return dereferenceable(24) [[P:%.*]]) #[[ATTR0]] {
// OBJC-NEXT:  [[ENTRY:.*:]]
// OBJC-NEXT:    [[P_INDIRECT_ADDR:%.*]] = alloca ptr, align 8
// OBJC-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    store ptr [[P]], ptr [[P_INDIRECT_ADDR]], align 8
// OBJC-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[P]], i64 24, i1 false)
// OBJC-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OBJC-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OBJC-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OBJC-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// OBJC-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// OBJC-NEXT:    store ptr @a, ptr [[TMP0]], align 8
// OBJC-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// OBJC-NEXT:    store ptr getelementptr inbounds nuw (i8, ptr @a, i64 80), ptr [[TMP1]], align 8
// OBJC-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// OBJC-NEXT:    store ptr @a, ptr [[TMP2]], align 8
// OBJC-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// OBJC-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP3]], align 8
// OBJC-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i64, ptr [[TMP4]], i64 1
// OBJC-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// OBJC-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP5]], align 8
// OBJC-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// OBJC-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
// OBJC-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// OBJC-NEXT:    store ptr [[TMP7]], ptr [[TMP8]], align 8
// OBJC-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// OBJC-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[TMP9]], align 8
// OBJC-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2
// OBJC-NEXT:    store ptr [[TMP10]], ptr [[TMP11]], align 8
// OBJC-NEXT:    [[WIDE_PTR_PTR_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// OBJC-NEXT:    [[WIDE_PTR_PTR3:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR2]], align 8
// OBJC-NEXT:    [[WIDE_PTR_UB_ADDR4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// OBJC-NEXT:    [[WIDE_PTR_UB5:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR4]], align 8
// OBJC-NEXT:    [[WIDE_PTR_LB_ADDR6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2
// OBJC-NEXT:    [[WIDE_PTR_LB7:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR6]], align 8
// OBJC-NEXT:    [[TMP12:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// OBJC-NEXT:    [[TMP13:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR3]] to i64
// OBJC-NEXT:    [[TMP14:%.*]] = call i64 @llvm.ptrauth.sign.generic(i64 [[TMP12]], i64 [[TMP13]])
// OBJC-NEXT:    ret i64 [[TMP14]]
//
unsigned long sign_generic_wide(unsigned long *__bidi_indexable p) {
  return __builtin_ptrauth_sign_generic_data(p, &a[1]);
}

// A wide pointer in the discriminator slot of auth / sign / resign, whose value
// operand stays __single so the result type is unaffected.
// C-LABEL: define dso_local ptr @auth_wide_disc(
// C-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// C-NEXT:  [[ENTRY:.*:]]
// C-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// C-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// C-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// C-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// C-NEXT:    store ptr @a, ptr [[TMP1]], align 8
// C-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// C-NEXT:    store ptr getelementptr inbounds nuw (i8, ptr @a, i64 80), ptr [[TMP2]], align 8
// C-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// C-NEXT:    store ptr @a, ptr [[TMP3]], align 8
// C-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// C-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP4]], align 8
// C-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i64, ptr [[TMP5]], i64 1
// C-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// C-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP6]], align 8
// C-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// C-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[TMP7]], align 8
// C-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// C-NEXT:    store ptr [[TMP8]], ptr [[TMP9]], align 8
// C-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// C-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[TMP10]], align 8
// C-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// C-NEXT:    store ptr [[TMP11]], ptr [[TMP12]], align 8
// C-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// C-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// C-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// C-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// C-NEXT:    [[TMP13:%.*]] = ptrtoint ptr [[TMP0]] to i64
// C-NEXT:    [[TMP14:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// C-NEXT:    [[TMP15:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[TMP13]], i32 2, i64 [[TMP14]])
// C-NEXT:    [[TMP16:%.*]] = inttoptr i64 [[TMP15]] to ptr
// C-NEXT:    ret ptr [[TMP16]]
//
// OBJC-LABEL: define dso_local ptr @auth_wide_disc(
// OBJC-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// OBJC-NEXT:  [[ENTRY:.*:]]
// OBJC-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// OBJC-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// OBJC-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// OBJC-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// OBJC-NEXT:    store ptr @a, ptr [[TMP1]], align 8
// OBJC-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// OBJC-NEXT:    store ptr getelementptr inbounds nuw (i8, ptr @a, i64 80), ptr [[TMP2]], align 8
// OBJC-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// OBJC-NEXT:    store ptr @a, ptr [[TMP3]], align 8
// OBJC-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// OBJC-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP4]], align 8
// OBJC-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i64, ptr [[TMP5]], i64 1
// OBJC-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OBJC-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP6]], align 8
// OBJC-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// OBJC-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[TMP7]], align 8
// OBJC-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OBJC-NEXT:    store ptr [[TMP8]], ptr [[TMP9]], align 8
// OBJC-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// OBJC-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[TMP10]], align 8
// OBJC-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OBJC-NEXT:    store ptr [[TMP11]], ptr [[TMP12]], align 8
// OBJC-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OBJC-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OBJC-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OBJC-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// OBJC-NEXT:    [[TMP13:%.*]] = ptrtoint ptr [[TMP0]] to i64
// OBJC-NEXT:    [[TMP14:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// OBJC-NEXT:    [[TMP15:%.*]] = call i64 @llvm.ptrauth.auth(i64 [[TMP13]], i32 2, i64 [[TMP14]])
// OBJC-NEXT:    [[TMP16:%.*]] = inttoptr i64 [[TMP15]] to ptr
// OBJC-NEXT:    ret ptr [[TMP16]]
//
unsigned long *__single auth_wide_disc(unsigned long *__single p) {
  return __builtin_ptrauth_auth(p, 2, &a[1]);
}

// C-LABEL: define dso_local ptr @sign_wide_disc(
// C-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// C-NEXT:  [[ENTRY:.*:]]
// C-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// C-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// C-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// C-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// C-NEXT:    store ptr @a, ptr [[TMP1]], align 8
// C-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// C-NEXT:    store ptr getelementptr inbounds nuw (i8, ptr @a, i64 80), ptr [[TMP2]], align 8
// C-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// C-NEXT:    store ptr @a, ptr [[TMP3]], align 8
// C-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// C-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP4]], align 8
// C-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i64, ptr [[TMP5]], i64 1
// C-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// C-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP6]], align 8
// C-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// C-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[TMP7]], align 8
// C-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// C-NEXT:    store ptr [[TMP8]], ptr [[TMP9]], align 8
// C-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// C-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[TMP10]], align 8
// C-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// C-NEXT:    store ptr [[TMP11]], ptr [[TMP12]], align 8
// C-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// C-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// C-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// C-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// C-NEXT:    [[TMP13:%.*]] = ptrtoint ptr [[TMP0]] to i64
// C-NEXT:    [[TMP14:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// C-NEXT:    [[TMP15:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[TMP13]], i32 2, i64 [[TMP14]])
// C-NEXT:    [[TMP16:%.*]] = inttoptr i64 [[TMP15]] to ptr
// C-NEXT:    ret ptr [[TMP16]]
//
// OBJC-LABEL: define dso_local ptr @sign_wide_disc(
// OBJC-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// OBJC-NEXT:  [[ENTRY:.*:]]
// OBJC-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// OBJC-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// OBJC-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// OBJC-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// OBJC-NEXT:    store ptr @a, ptr [[TMP1]], align 8
// OBJC-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// OBJC-NEXT:    store ptr getelementptr inbounds nuw (i8, ptr @a, i64 80), ptr [[TMP2]], align 8
// OBJC-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// OBJC-NEXT:    store ptr @a, ptr [[TMP3]], align 8
// OBJC-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// OBJC-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP4]], align 8
// OBJC-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i64, ptr [[TMP5]], i64 1
// OBJC-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OBJC-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP6]], align 8
// OBJC-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// OBJC-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[TMP7]], align 8
// OBJC-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OBJC-NEXT:    store ptr [[TMP8]], ptr [[TMP9]], align 8
// OBJC-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// OBJC-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[TMP10]], align 8
// OBJC-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OBJC-NEXT:    store ptr [[TMP11]], ptr [[TMP12]], align 8
// OBJC-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OBJC-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OBJC-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OBJC-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// OBJC-NEXT:    [[TMP13:%.*]] = ptrtoint ptr [[TMP0]] to i64
// OBJC-NEXT:    [[TMP14:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// OBJC-NEXT:    [[TMP15:%.*]] = call i64 @llvm.ptrauth.sign(i64 [[TMP13]], i32 2, i64 [[TMP14]])
// OBJC-NEXT:    [[TMP16:%.*]] = inttoptr i64 [[TMP15]] to ptr
// OBJC-NEXT:    ret ptr [[TMP16]]
//
unsigned long *__single sign_wide_disc(unsigned long *__single p) {
  return __builtin_ptrauth_sign_unauthenticated(p, 2, &a[1]);
}

// C-LABEL: define dso_local ptr @resign_wide_disc(
// C-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// C-NEXT:  [[ENTRY:.*:]]
// C-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// C-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    [[TMP_TMP2:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// C-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// C-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// C-NEXT:    store ptr @a, ptr [[TMP1]], align 8
// C-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// C-NEXT:    store ptr getelementptr inbounds nuw (i8, ptr @a, i64 80), ptr [[TMP2]], align 8
// C-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// C-NEXT:    store ptr @a, ptr [[TMP3]], align 8
// C-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// C-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP4]], align 8
// C-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i64, ptr [[TMP5]], i64 1
// C-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// C-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP6]], align 8
// C-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// C-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[TMP7]], align 8
// C-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// C-NEXT:    store ptr [[TMP8]], ptr [[TMP9]], align 8
// C-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// C-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[TMP10]], align 8
// C-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// C-NEXT:    store ptr [[TMP11]], ptr [[TMP12]], align 8
// C-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// C-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// C-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// C-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// C-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP2]], i32 0, i32 0
// C-NEXT:    store ptr @a, ptr [[TMP13]], align 8
// C-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP2]], i32 0, i32 1
// C-NEXT:    store ptr getelementptr inbounds nuw (i8, ptr @a, i64 80), ptr [[TMP14]], align 8
// C-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP2]], i32 0, i32 2
// C-NEXT:    store ptr @a, ptr [[TMP15]], align 8
// C-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP2]], i32 0, i32 0
// C-NEXT:    [[TMP17:%.*]] = load ptr, ptr [[TMP16]], align 8
// C-NEXT:    [[BOUND_PTR_ARITH3:%.*]] = getelementptr i64, ptr [[TMP17]], i64 2
// C-NEXT:    [[TMP18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// C-NEXT:    store ptr [[BOUND_PTR_ARITH3]], ptr [[TMP18]], align 8
// C-NEXT:    [[TMP19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP2]], i32 0, i32 1
// C-NEXT:    [[TMP20:%.*]] = load ptr, ptr [[TMP19]], align 8
// C-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// C-NEXT:    store ptr [[TMP20]], ptr [[TMP21]], align 8
// C-NEXT:    [[TMP22:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP2]], i32 0, i32 2
// C-NEXT:    [[TMP23:%.*]] = load ptr, ptr [[TMP22]], align 8
// C-NEXT:    [[TMP24:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2
// C-NEXT:    store ptr [[TMP23]], ptr [[TMP24]], align 8
// C-NEXT:    [[WIDE_PTR_PTR_ADDR4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// C-NEXT:    [[WIDE_PTR_PTR5:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR4]], align 8
// C-NEXT:    [[WIDE_PTR_UB_ADDR6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// C-NEXT:    [[WIDE_PTR_UB7:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR6]], align 8
// C-NEXT:    [[WIDE_PTR_LB_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2
// C-NEXT:    [[WIDE_PTR_LB9:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR8]], align 8
// C-NEXT:    [[TMP25:%.*]] = ptrtoint ptr [[TMP0]] to i64
// C-NEXT:    [[TMP26:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR5]] to i64
// C-NEXT:    [[TMP27:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// C-NEXT:    [[TMP28:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[TMP25]], i32 2, i64 [[TMP27]], i32 2, i64 [[TMP26]])
// C-NEXT:    [[TMP29:%.*]] = inttoptr i64 [[TMP28]] to ptr
// C-NEXT:    ret ptr [[TMP29]]
//
// OBJC-LABEL: define dso_local ptr @resign_wide_disc(
// OBJC-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// OBJC-NEXT:  [[ENTRY:.*:]]
// OBJC-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// OBJC-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    [[TMP_TMP2:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// OBJC-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// OBJC-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// OBJC-NEXT:    store ptr @a, ptr [[TMP1]], align 8
// OBJC-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// OBJC-NEXT:    store ptr getelementptr inbounds nuw (i8, ptr @a, i64 80), ptr [[TMP2]], align 8
// OBJC-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// OBJC-NEXT:    store ptr @a, ptr [[TMP3]], align 8
// OBJC-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// OBJC-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[TMP4]], align 8
// OBJC-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i64, ptr [[TMP5]], i64 1
// OBJC-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OBJC-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP6]], align 8
// OBJC-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// OBJC-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[TMP7]], align 8
// OBJC-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OBJC-NEXT:    store ptr [[TMP8]], ptr [[TMP9]], align 8
// OBJC-NEXT:    [[TMP10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// OBJC-NEXT:    [[TMP11:%.*]] = load ptr, ptr [[TMP10]], align 8
// OBJC-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OBJC-NEXT:    store ptr [[TMP11]], ptr [[TMP12]], align 8
// OBJC-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OBJC-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OBJC-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OBJC-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// OBJC-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP2]], i32 0, i32 0
// OBJC-NEXT:    store ptr @a, ptr [[TMP13]], align 8
// OBJC-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP2]], i32 0, i32 1
// OBJC-NEXT:    store ptr getelementptr inbounds nuw (i8, ptr @a, i64 80), ptr [[TMP14]], align 8
// OBJC-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP2]], i32 0, i32 2
// OBJC-NEXT:    store ptr @a, ptr [[TMP15]], align 8
// OBJC-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP2]], i32 0, i32 0
// OBJC-NEXT:    [[TMP17:%.*]] = load ptr, ptr [[TMP16]], align 8
// OBJC-NEXT:    [[BOUND_PTR_ARITH3:%.*]] = getelementptr i64, ptr [[TMP17]], i64 2
// OBJC-NEXT:    [[TMP18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// OBJC-NEXT:    store ptr [[BOUND_PTR_ARITH3]], ptr [[TMP18]], align 8
// OBJC-NEXT:    [[TMP19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP2]], i32 0, i32 1
// OBJC-NEXT:    [[TMP20:%.*]] = load ptr, ptr [[TMP19]], align 8
// OBJC-NEXT:    [[TMP21:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// OBJC-NEXT:    store ptr [[TMP20]], ptr [[TMP21]], align 8
// OBJC-NEXT:    [[TMP22:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP_TMP2]], i32 0, i32 2
// OBJC-NEXT:    [[TMP23:%.*]] = load ptr, ptr [[TMP22]], align 8
// OBJC-NEXT:    [[TMP24:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2
// OBJC-NEXT:    store ptr [[TMP23]], ptr [[TMP24]], align 8
// OBJC-NEXT:    [[WIDE_PTR_PTR_ADDR4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// OBJC-NEXT:    [[WIDE_PTR_PTR5:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR4]], align 8
// OBJC-NEXT:    [[WIDE_PTR_UB_ADDR6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// OBJC-NEXT:    [[WIDE_PTR_UB7:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR6]], align 8
// OBJC-NEXT:    [[WIDE_PTR_LB_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2
// OBJC-NEXT:    [[WIDE_PTR_LB9:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR8]], align 8
// OBJC-NEXT:    [[TMP25:%.*]] = ptrtoint ptr [[TMP0]] to i64
// OBJC-NEXT:    [[TMP26:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR5]] to i64
// OBJC-NEXT:    [[TMP27:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// OBJC-NEXT:    [[TMP28:%.*]] = call i64 @llvm.ptrauth.resign(i64 [[TMP25]], i32 2, i64 [[TMP27]], i32 2, i64 [[TMP26]])
// OBJC-NEXT:    [[TMP29:%.*]] = inttoptr i64 [[TMP28]] to ptr
// OBJC-NEXT:    ret ptr [[TMP29]]
//
unsigned long *__single resign_wide_disc(unsigned long *__single p) {
  return __builtin_ptrauth_auth_and_resign(p, 2, &a[1], 2, &a[2]);
}

//===----------------------------------------------------------------------===//
// Operands that already had raw pointer layout must be completely unchanged.
//===----------------------------------------------------------------------===//

// __counted_by keeps its bounds in a separate field, so the pointer itself is
// raw-layout and never went through the broken path.
// C-LABEL: define dso_local i64 @counted_by_unchanged(
// C-SAME: ptr noundef [[P:%.*]], i32 noundef [[N:%.*]]) #[[ATTR0]] {
// C-NEXT:  [[ENTRY:.*:]]
// C-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// C-NEXT:    [[N_ADDR:%.*]] = alloca i32, align 4
// C-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// C-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// C-NEXT:    store i32 [[N]], ptr [[N_ADDR]], align 4
// C-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// C-NEXT:    [[TMP1:%.*]] = load i32, ptr [[N_ADDR]], align 4
// C-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP1]] to i64
// C-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i64, ptr [[TMP0]], i64 [[IDX_EXT]]
// C-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// C-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8
// C-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// C-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP3]], align 8
// C-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// C-NEXT:    store ptr [[TMP0]], ptr [[TMP4]], align 8
// C-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// C-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// C-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// C-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// C-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// C-NEXT:    [[TMP5:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// C-NEXT:    [[TMP6:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[TMP5]], i64 42)
// C-NEXT:    ret i64 [[TMP6]]
//
// OBJC-LABEL: define dso_local i64 @counted_by_unchanged(
// OBJC-SAME: ptr noundef [[P:%.*]], i32 noundef [[N:%.*]]) #[[ATTR0]] {
// OBJC-NEXT:  [[ENTRY:.*:]]
// OBJC-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// OBJC-NEXT:    [[N_ADDR:%.*]] = alloca i32, align 4
// OBJC-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// OBJC-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// OBJC-NEXT:    store i32 [[N]], ptr [[N_ADDR]], align 4
// OBJC-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// OBJC-NEXT:    [[TMP1:%.*]] = load i32, ptr [[N_ADDR]], align 4
// OBJC-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP1]] to i64
// OBJC-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i64, ptr [[TMP0]], i64 [[IDX_EXT]]
// OBJC-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OBJC-NEXT:    store ptr [[TMP0]], ptr [[TMP2]], align 8
// OBJC-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OBJC-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP3]], align 8
// OBJC-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OBJC-NEXT:    store ptr [[TMP0]], ptr [[TMP4]], align 8
// OBJC-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// OBJC-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// OBJC-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// OBJC-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// OBJC-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// OBJC-NEXT:    [[TMP5:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64
// OBJC-NEXT:    [[TMP6:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[TMP5]], i64 42)
// OBJC-NEXT:    ret i64 [[TMP6]]
//
unsigned long counted_by_unchanged(unsigned long *__counted_by(n) p, int n) {
  return __builtin_ptrauth_blend_discriminator(p, 42);
}

// C-LABEL: define dso_local i64 @single_unchanged(
// C-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// C-NEXT:  [[ENTRY:.*:]]
// C-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// C-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// C-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// C-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[TMP0]] to i64
// C-NEXT:    [[TMP2:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[TMP1]], i64 42)
// C-NEXT:    ret i64 [[TMP2]]
//
// OBJC-LABEL: define dso_local i64 @single_unchanged(
// OBJC-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// OBJC-NEXT:  [[ENTRY:.*:]]
// OBJC-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// OBJC-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// OBJC-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// OBJC-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[TMP0]] to i64
// OBJC-NEXT:    [[TMP2:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[TMP1]], i64 42)
// OBJC-NEXT:    ret i64 [[TMP2]]
//
unsigned long single_unchanged(unsigned long *__single p) {
  return __builtin_ptrauth_blend_discriminator(p, 42);
}

// C-LABEL: define dso_local i64 @unsafe_unchanged(
// C-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// C-NEXT:  [[ENTRY:.*:]]
// C-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// C-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// C-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// C-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[TMP0]] to i64
// C-NEXT:    [[TMP2:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[TMP1]], i64 42)
// C-NEXT:    ret i64 [[TMP2]]
//
// OBJC-LABEL: define dso_local i64 @unsafe_unchanged(
// OBJC-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// OBJC-NEXT:  [[ENTRY:.*:]]
// OBJC-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// OBJC-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// OBJC-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// OBJC-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[TMP0]] to i64
// OBJC-NEXT:    [[TMP2:%.*]] = call i64 @llvm.ptrauth.blend(i64 [[TMP1]], i64 42)
// OBJC-NEXT:    ret i64 [[TMP2]]
//
unsigned long unsafe_unchanged(unsigned long *__unsafe_indexable p) {
  return __builtin_ptrauth_blend_discriminator(p, 42);
}

// C-LABEL: define dso_local ptr @strip_single_unchanged(
// C-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// C-NEXT:  [[ENTRY:.*:]]
// C-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// C-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// C-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// C-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[TMP0]] to i64
// C-NEXT:    [[TMP2:%.*]] = call i64 @llvm.ptrauth.strip(i64 [[TMP1]], i32 2)
// C-NEXT:    [[TMP3:%.*]] = inttoptr i64 [[TMP2]] to ptr
// C-NEXT:    ret ptr [[TMP3]]
//
// OBJC-LABEL: define dso_local ptr @strip_single_unchanged(
// OBJC-SAME: ptr noundef [[P:%.*]]) #[[ATTR0]] {
// OBJC-NEXT:  [[ENTRY:.*:]]
// OBJC-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// OBJC-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// OBJC-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// OBJC-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[TMP0]] to i64
// OBJC-NEXT:    [[TMP2:%.*]] = call i64 @llvm.ptrauth.strip(i64 [[TMP1]], i32 2)
// OBJC-NEXT:    [[TMP3:%.*]] = inttoptr i64 [[TMP2]] to ptr
// OBJC-NEXT:    ret ptr [[TMP3]]
//
unsigned long *__single strip_single_unchanged(unsigned long *__single p) {
  return __builtin_ptrauth_strip(p, 2);
}

//.
// C: [[META4]] = !{!"bounds-safety-check-ptr-le-upper-bound"}
// C: [[PROF5]] = !{!"branch_weights", i32 1048575, i32 1}
// C: [[META6]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
// C: [[LOOP7]] = distinct !{[[LOOP7]], [[META8:![0-9]+]]}
// C: [[META8]] = !{!"llvm.loop.mustprogress"}
//.
// OBJC: [[META10]] = !{!"bounds-safety-check-ptr-le-upper-bound"}
// OBJC: [[PROF11]] = !{!"branch_weights", i32 1048575, i32 1}
// OBJC: [[META12]] = !{!"bounds-safety-check-ptr-ge-lower-bound"}
// OBJC: [[LOOP13]] = distinct !{[[LOOP13]], [[META14:![0-9]+]]}
// OBJC: [[META14]] = !{!"llvm.loop.mustprogress"}
//.
