; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2

; Check that we default to -aarch64-cfi-llvm-set-ra-sign-state=never on Mach-O
; platforms, and -aarch64-cfi-llvm-set-ra-sign-state=pauth-lr on ELF platforms.

; RUN: llc -mtriple=arm64e-apple-ios -mattr=v9a -mattr=pauth-lr < %s                                              | FileCheck %s --check-prefix=MACHO-NEGATE-PAUTHLR
; RUN: llc -mtriple=arm64e-apple-ios -mattr=v9a -mattr=pauth-lr -aarch64-cfi-llvm-set-ra-sign-state=never < %s    | FileCheck %s --check-prefix=MACHO-NEGATE-PAUTHLR
; RUN: llc -mtriple=arm64e-apple-ios -mattr=v9a -mattr=pauth-lr -aarch64-cfi-llvm-set-ra-sign-state=pauth-lr < %s | FileCheck %s --check-prefix=MACHO-SET-PAUTHLR
; RUN: llc -mtriple=arm64e-apple-ios -mattr=v9a -mattr=pauth-lr -aarch64-cfi-llvm-set-ra-sign-state=always < %s   | FileCheck %s --check-prefix=MACHO-SET-PAUTHLR

; RUN: llc -mtriple=aarch64 -mattr=v9a -mattr=pauth-lr < %s                                              | FileCheck %s --check-prefix=ELF-NEGATE-PAUTHLR
; RUN: llc -mtriple=aarch64 -mattr=v9a -mattr=pauth-lr -aarch64-cfi-llvm-set-ra-sign-state=never < %s    | FileCheck %s --check-prefix=ELF-NEGATE-PAUTHLR
; RUN: llc -mtriple=aarch64 -mattr=v9a -mattr=pauth-lr -aarch64-cfi-llvm-set-ra-sign-state=pauth-lr < %s | FileCheck %s --check-prefix=ELF-SET-PAUTHLR
; RUN: llc -mtriple=aarch64 -mattr=v9a -mattr=pauth-lr -aarch64-cfi-llvm-set-ra-sign-state=always < %s   | FileCheck %s --check-prefix=ELF-SET-PAUTHLR

; RUN: llc -mtriple=arm64e-apple-ios < %s                                              | FileCheck %s --check-prefix=MACHO-NEGATE-PAUTH
; RUN: llc -mtriple=arm64e-apple-ios -aarch64-cfi-llvm-set-ra-sign-state=never < %s    | FileCheck %s --check-prefix=MACHO-NEGATE-PAUTH
; RUN: llc -mtriple=arm64e-apple-ios -aarch64-cfi-llvm-set-ra-sign-state=pauth-lr < %s | FileCheck %s --check-prefix=MACHO-SET-PAUTH
; RUN: llc -mtriple=arm64e-apple-ios -aarch64-cfi-llvm-set-ra-sign-state=always < %s   | FileCheck %s --check-prefix=MACHO-SET-PAUTH

; RUN: llc -mtriple=aarch64 < %s                                              | FileCheck %s --check-prefix=ELF-NEGATE-PAUTH
; RUN: llc -mtriple=aarch64 -aarch64-cfi-llvm-set-ra-sign-state=never < %s    | FileCheck %s --check-prefix=ELF-NEGATE-PAUTH
; RUN: llc -mtriple=aarch64 -aarch64-cfi-llvm-set-ra-sign-state=pauth-lr < %s | FileCheck %s --check-prefix=ELF-SET-PAUTH
; RUN: llc -mtriple=aarch64 -aarch64-cfi-llvm-set-ra-sign-state=always < %s   | FileCheck %s --check-prefix=ELF-SET-PAUTH

define i32 @pauth_lr(i32 %x) "branch-protection-pauth-lr" "sign-return-address"="all" {
; MACHO-NEGATE-LABEL: leaf_sign_all:
; MACHO-NEGATE:       ; %bb.0:
; MACHO-NEGATE-NEXT:    .cfi_negate_ra_state_with_pc
; MACHO-NEGATE-NEXT:  Ltmp0:
; MACHO-NEGATE-NEXT:    paciasppc
; MACHO-NEGATE-NEXT:    retaasppc Ltmp0
;
; MACHO-SET-LABEL: leaf_sign_all:
; MACHO-SET:       ; %bb.0:
; MACHO-SET-NEXT:  Ltmp0:
; MACHO-SET-NEXT:    paciasppc
; MACHO-SET-NEXT:    .cfi_set_ra_state 2, Ltmp0
; MACHO-SET-NEXT:    retaasppc Ltmp0
; MACHO-NEGATE-PAUTHLR-LABEL: pauth_lr:
; MACHO-NEGATE-PAUTHLR:       ; %bb.0:
; MACHO-NEGATE-PAUTHLR-NEXT:    .cfi_negate_ra_state_with_pc
; MACHO-NEGATE-PAUTHLR-NEXT:  Ltmp0:
; MACHO-NEGATE-PAUTHLR-NEXT:    paciasppc
; MACHO-NEGATE-PAUTHLR-NEXT:    retaasppc Ltmp0
;
; MACHO-SET-PAUTHLR-LABEL: pauth_lr:
; MACHO-SET-PAUTHLR:       ; %bb.0:
; MACHO-SET-PAUTHLR-NEXT:  Ltmp0:
; MACHO-SET-PAUTHLR-NEXT:    paciasppc
; MACHO-SET-PAUTHLR-NEXT:    .cfi_set_ra_state 2, Ltmp0
; MACHO-SET-PAUTHLR-NEXT:    retaasppc Ltmp0
;
; ELF-SET-PAUTHLR-LABEL: pauth_lr:
; ELF-SET-PAUTHLR:       // %bb.0:
; ELF-SET-PAUTHLR-NEXT:  .Ltmp0:
; ELF-SET-PAUTHLR-NEXT:    paciasppc
; ELF-SET-PAUTHLR-NEXT:    .cfi_set_ra_state 2, .Ltmp0
; ELF-SET-PAUTHLR-NEXT:    retaasppc .Ltmp0
;
; MACHO-NEGATE-PAUTH-LABEL: pauth_lr:
; MACHO-NEGATE-PAUTH:       ; %bb.0:
; MACHO-NEGATE-PAUTH-NEXT:    hint #39
; MACHO-NEGATE-PAUTH-NEXT:    .cfi_negate_ra_state_with_pc
; MACHO-NEGATE-PAUTH-NEXT:  Ltmp0:
; MACHO-NEGATE-PAUTH-NEXT:    paciasp
; MACHO-NEGATE-PAUTH-NEXT:    adrp x16, Ltmp0@PAGE
; MACHO-NEGATE-PAUTH-NEXT:    add x16, x16, Ltmp0@PAGEOFF
; MACHO-NEGATE-PAUTH-NEXT:    hint #39
; MACHO-NEGATE-PAUTH-NEXT:    retaa
;
; MACHO-SET-PAUTH-LABEL: pauth_lr:
; MACHO-SET-PAUTH:       ; %bb.0:
; MACHO-SET-PAUTH-NEXT:    hint #39
; MACHO-SET-PAUTH-NEXT:  Ltmp0:
; MACHO-SET-PAUTH-NEXT:    paciasp
; MACHO-SET-PAUTH-NEXT:    .cfi_set_ra_state 2, Ltmp0
; MACHO-SET-PAUTH-NEXT:    adrp x16, Ltmp0@PAGE
; MACHO-SET-PAUTH-NEXT:    add x16, x16, Ltmp0@PAGEOFF
; MACHO-SET-PAUTH-NEXT:    hint #39
; MACHO-SET-PAUTH-NEXT:    retaa
;
; ELF-SET-PAUTH-LABEL: pauth_lr:
; ELF-SET-PAUTH:       // %bb.0:
; ELF-SET-PAUTH-NEXT:    hint #39
; ELF-SET-PAUTH-NEXT:  .Ltmp0:
; ELF-SET-PAUTH-NEXT:    hint #25
; ELF-SET-PAUTH-NEXT:    .cfi_set_ra_state 2, .Ltmp0
; ELF-SET-PAUTH-NEXT:    adrp x16, .Ltmp0
; ELF-SET-PAUTH-NEXT:    add x16, x16, :lo12:.Ltmp0
; ELF-SET-PAUTH-NEXT:    hint #39
; ELF-SET-PAUTH-NEXT:    hint #29
; ELF-SET-PAUTH-NEXT:    ret
  ret i32 %x
}

define i32 @pauth(i32 %x) "sign-return-address"="all" {
; MACHO-NEGATE-LABEL: leaf_sign_all:
; MACHO-NEGATE:       ; %bb.0:
; MACHO-NEGATE-NEXT:    .cfi_negate_ra_state_with_pc
; MACHO-NEGATE-NEXT:  Ltmp0:
; MACHO-NEGATE-NEXT:    paciasppc
; MACHO-NEGATE-NEXT:    retaasppc Ltmp0
;
; MACHO-SET-LABEL: leaf_sign_all:
; MACHO-SET:       ; %bb.0:
; MACHO-SET-NEXT:  Ltmp0:
; MACHO-SET-NEXT:    paciasppc
; MACHO-SET-NEXT:    .cfi_set_ra_state 2, Ltmp0
; MACHO-SET-NEXT:    retaasppc Ltmp0
; MACHO-NEGATE-PAUTHLR-LABEL: pauth:
; MACHO-NEGATE-PAUTHLR:       ; %bb.0:
; MACHO-NEGATE-PAUTHLR-NEXT:    paciasp
; MACHO-NEGATE-PAUTHLR-NEXT:    retaa
;
; ELF-NEGATE-PAUTHLR-LABEL: pauth:
; ELF-NEGATE-PAUTHLR:       // %bb.0:
; ELF-NEGATE-PAUTHLR-NEXT:    paciasp
; ELF-NEGATE-PAUTHLR-NEXT:    .cfi_negate_ra_state
; ELF-NEGATE-PAUTHLR-NEXT:    retaa
;
; MACHO-NEGATE-PAUTH-LABEL: pauth:
; MACHO-NEGATE-PAUTH:       ; %bb.0:
; MACHO-NEGATE-PAUTH-NEXT:    paciasp
; MACHO-NEGATE-PAUTH-NEXT:    retaa
;
; ELF-NEGATE-PAUTH-LABEL: pauth:
; ELF-NEGATE-PAUTH:       // %bb.0:
; ELF-NEGATE-PAUTH-NEXT:    hint #25
; ELF-NEGATE-PAUTH-NEXT:    .cfi_negate_ra_state
; ELF-NEGATE-PAUTH-NEXT:    hint #29
; ELF-NEGATE-PAUTH-NEXT:    ret
  ret i32 %x
}
