; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple arm64e-apple-darwin             -verify-machineinstrs -stop-after=finalize-isel -global-isel=0 \
; RUN:     | FileCheck %s --check-prefixes=DAGISEL-DARWIN
; RUN: llc < %s -mtriple arm64e-apple-darwin             -verify-machineinstrs -stop-after=finalize-isel -global-isel=1 -global-isel-abort=1 \
; RUN:     | FileCheck %s --check-prefixes=GISEL-DARWIN
; RUN: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth -verify-machineinstrs -stop-after=finalize-isel -global-isel=0 \
; RUN:     | FileCheck %s --check-prefixes=DAGISEL-GNU
; RUN: llc < %s -mtriple aarch64-linux-gnu -mattr=+pauth -verify-machineinstrs -stop-after=finalize-isel -global-isel=1 -global-isel-abort=1 \
; RUN:     | FileCheck %s --check-prefixes=GISEL-GNU

; Check MIR produced by the instruction selector to validate properties that
; cannot be reliably tested by only inspecting the final asm output.

; On non-Darwin platforms, AUTxMxN allows allocating arbitrary scratch registers.
; To simplify expansion of AUTxMxN in AArch64AsmPrinter, $Scratch operand
; should be marked as @earlyclobber, which is checked by this test case.
define i64 @autxmxn_earlyclobbered_scratch(i64 %addr, i64 %disc) {
  ; DAGISEL-DARWIN-LABEL: name: autxmxn_earlyclobbered_scratch
  ; DAGISEL-DARWIN: bb.0.entry:
  ; DAGISEL-DARWIN-NEXT:   liveins: $x0, $x1
  ; DAGISEL-DARWIN-NEXT: {{  $}}
  ; DAGISEL-DARWIN-NEXT:   [[COPY:%[0-9]+]]:gpr64noip = COPY $x1
  ; DAGISEL-DARWIN-NEXT:   [[COPY1:%[0-9]+]]:gpr64 = COPY $x0
  ; DAGISEL-DARWIN-NEXT:   $x16 = COPY [[COPY1]]
  ; DAGISEL-DARWIN-NEXT:   AUTx16x17 2, 0, [[COPY]], implicit-def $x16, implicit-def dead $x17, implicit-def dead $nzcv, implicit $x16
  ; DAGISEL-DARWIN-NEXT:   [[COPY2:%[0-9]+]]:gpr64all = COPY $x16
  ; DAGISEL-DARWIN-NEXT:   $x0 = COPY [[COPY2]]
  ; DAGISEL-DARWIN-NEXT:   RET_ReallyLR implicit $x0
  ;
  ; GISEL-DARWIN-LABEL: name: autxmxn_earlyclobbered_scratch
  ; GISEL-DARWIN: bb.1.entry:
  ; GISEL-DARWIN-NEXT:   liveins: $x0, $x1
  ; GISEL-DARWIN-NEXT: {{  $}}
  ; GISEL-DARWIN-NEXT:   [[COPY:%[0-9]+]]:gpr64all = COPY $x0
  ; GISEL-DARWIN-NEXT:   [[COPY1:%[0-9]+]]:gpr64noip = COPY $x1
  ; GISEL-DARWIN-NEXT:   $x16 = COPY [[COPY]]
  ; GISEL-DARWIN-NEXT:   $x17 = IMPLICIT_DEF
  ; GISEL-DARWIN-NEXT:   AUTx16x17 2, 0, [[COPY1]], implicit-def $x16, implicit-def $x17, implicit-def dead $nzcv, implicit $x16
  ; GISEL-DARWIN-NEXT:   [[COPY2:%[0-9]+]]:gpr64 = COPY $x16
  ; GISEL-DARWIN-NEXT:   $x0 = COPY [[COPY2]]
  ; GISEL-DARWIN-NEXT:   RET_ReallyLR implicit $x0
  ;
  ; DAGISEL-GNU-LABEL: name: autxmxn_earlyclobbered_scratch
  ; DAGISEL-GNU: bb.0.entry:
  ; DAGISEL-GNU-NEXT:   liveins: $x0, $x1
  ; DAGISEL-GNU-NEXT: {{  $}}
  ; DAGISEL-GNU-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY $x1
  ; DAGISEL-GNU-NEXT:   [[COPY1:%[0-9]+]]:gpr64 = COPY $x0
  ; DAGISEL-GNU-NEXT:   %2:gpr64, early-clobber %3:gpr64common = AUTxMxN [[COPY1]], 2, 0, [[COPY]], implicit-def dead $nzcv
  ; DAGISEL-GNU-NEXT:   $x0 = COPY %2
  ; DAGISEL-GNU-NEXT:   RET_ReallyLR implicit $x0
  ;
  ; GISEL-GNU-LABEL: name: autxmxn_earlyclobbered_scratch
  ; GISEL-GNU: bb.1.entry:
  ; GISEL-GNU-NEXT:   liveins: $x0, $x1
  ; GISEL-GNU-NEXT: {{  $}}
  ; GISEL-GNU-NEXT:   [[COPY:%[0-9]+]]:gpr64 = COPY $x0
  ; GISEL-GNU-NEXT:   [[COPY1:%[0-9]+]]:gpr64 = COPY $x1
  ; GISEL-GNU-NEXT:   %2:gpr64, early-clobber %3:gpr64common = AUTxMxN [[COPY]], 2, 0, [[COPY1]], implicit-def dead $nzcv
  ; GISEL-GNU-NEXT:   $x0 = COPY %2
  ; GISEL-GNU-NEXT:   RET_ReallyLR implicit $x0
entry:
  %auted = call i64 @llvm.ptrauth.auth(i64 %addr, i32 2, i64 %disc)
  ret i64 %auted
}
