SWIFT_SOURCES := main.swift
SWIFT_ENABLE_COMPILE_CACHE := YES
# Without a .swiftmodule embedded in the binary, the CAS is the only place the
# main module can come from.
HIDE_SWIFTMODULE := YES

include Makefile.rules
