C_SOURCES := \
  main.c \
  bidi_check_known_type_size.c \
  bidi_check_unknown_type_size.c \
  idx_check_known_type_size.c \
  idx_check_unknown_type_size.c

CFLAGS_EXTRAS := -fbounds-safety

include Makefile.rules
